// 64x64
const stick_base = atob("QEABAAAAD/4AAAAAAAP///gAAAAAD////gAAAAB/////wAAAAP/////gAAAD//////gAAAf//////AAAB//////8AAAP//////4AAA///////gAAD///////AAAP//////8AAA///////gAAD//////+AAAH//////wAAAf//////4AAAf//////+AAA///////wAAB/////z/AAAA////4f4AAAAf//8D/AAAAB//+Af4AAAAP//+D/gAAAB////P8AAAAf/w///gAAAD//D//8AAAAf///P/gAAAD///+H8AAAAf///4AAAAAD///gAAAAAAH//gAAAAAAAH/8AAAAAAAAA/gAAAAAAAAD+AAAAAAAAAf4AAAAAAAAB/AAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAf+AAAAAAAAB/8AAAAAAAAP/4AAAAAAAB//4AAAAAAAH//wAAAAAAA/x/wAAAAAAD+D/gAAAAAAf4H/AAAAAAB/AH/AAAAAAP8AP+AAAAAB/gAP8AAAAAP8AAf8AAAAB/wAA/wAAAAP+AAD/AAAAB/gAAP8AAAAP8AAA/wAAAB/gAAD/AAAAP8AAAP8AAAB/gAAA/wAAAP8AAAD/AAAB/gAAAP8AAAP8AAAA/wAAB/gAAAD/AAAD8AAAAH8AAAAgAAAAAAAAA=");

// 64x64
const stick_jab_l_1 = atob("QEABAAAAAAAAAAAAAf//AAAAAAAP///wAAAAAH////wAAAAB/////wAAAAf/////wAAAD//////gAAAP//////AAAD//////+AAAP//////4AAA///////gAAD///////AAAP//////8AAA///////gAAD//////+AAAH//////4AAAP/////+AAAAf/////wAAAA/////+AAAAA/////gAAAAA////4AAAAAA////vAAAAAAP///+AAAAAAH+P/8AAAAAA////AAAAAAD///gAAAAAAf//wAAAAAAD//4AAAAAAAP//AAAAAAAAf/wAAAAAAAB/+AAAAAAAAH/wAAAAAAAAf4AAAAAAAAB/AAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD+AAAAAAAAAP4AAAAAAAAA/gAAAAAAAAD+AAAAAAAAAP4AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP+AAAAAAAAA/4AAAAAAAAD/wAAAAAAAAP/AAAAAAAAAf+AAAAAAAAB/4AAAAAAAAH/wAAAAAAAAf/gAAAAAAAB/+AAAAAAAAP/4AAAAAAAD//gAAAAAAAf/+AAAAAAAH//4AAAAAAA/4/gAAAAAAP/H+AAAAAAB/wf4AAAAAAf8B/gAAAAAD/gH+AAAAAA/4Af4AAAAAA/AB/gAAAAAAwAD8AAAAAA=");

// 64x64
const stick_jab_l_2 = atob("QEABAAB/+AAAAAAAD///4AAAAAB////4AAAAAf////4AAAAH/////4AAAA//////wAAAH//////gAAA///////AAAD//////+AAAf//////4AAB///////gAAH//////+AAAf//////4AAA///////gAAD//////8AAAH//////gAAAP/////8AAAAf/////gAAAAf/////AAAAAf////+AAAAAP////////AAB///////8AAA///////wAAD///////AAAP9//4AAAAAA/wf/AAAAAAD/ADgAAAAAAP8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP+AAAAAAAAB/8AAAAAAAAH/4AAAAAAAAP/wAAAAAAAA//wAAAAAAAD//gAAAAAAAP//gAAAAAAAf//AAAAAAAB/v+AAAAAAAD+f4AAAAAAAP//AAAAAAAA//4AAAAAAAB//AAAAAAAAH/wAAAAAAAAf+AAAAAAAAD/wAAAAAAAAf8AAAAAAAAD/gAAAAAAAAf8AAAAAAAAB/gAAAAAAAAH8AAAAAAAAAfwAAAAAAAAD/AAAAAAAAAH4AAAAAAAAAAAAAAAAA=");

// 64x64
const stick_jab_r_1 = atob("QEABAAD/8AAAAAAAH///wAAAAAD////wAAAAA/////wAAAAH/////wAAAB//////gAAAP//////AAAA//////+AAAH//////8AAA///////wAAD///////AAAP//////8AAA///////wAAB///////AAAH//////4AAAP//////AAAAf/////4AAAA//////AAAAA/////wAAAAA////8AAAHwAP///wAAP/AB/////4f/8Af////////wH////////gA////////AAB///8AAfAAAD/f8AAAAAAAAA/gAAAAAAAAD+AAAAAAAAAP4AAAAAAAAA/gAAAAAAAAD+AAAAAAAAAP4AAAAAAAAA/gAAAAAAAAH+AAAAAAAAAfwAAAAAAAAB/AAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP+AAAAAAAAB/+AAAAAAAAP/8AAAAAAAB//4AAAAAAAP//wAAAAAAB/h/gAAAAAAP8D/AAAAAAB/gH+AAAAAAf8AP8AAAAAD/gAf8AAAAAP8AA/4AAAAA/gAB/gAAAAH+AAD+AAAAAfwAAP4AAAAB/AAA/gAAAAP8AAD+AAAAA/gAAP4AAAAH+AAA/gAAAAfwAAD+AAAAB/AAAP4AAAAP8AAA/gAAAA/gAAD+AAAAD+AAAP4AAAAAAAAAAAAAAA=");

// 64x64
const stick_jab_r_2 = atob("QEABAAB/+AAAAAAAH///wAAAAAB////4AAAAA/////4AAAAH/////wAAAB//////wAAAP//////gAAA//////+AAAH//////8AAAf//////4AAB///////gAAH//////+AAAf//////4AAB///////AAAD//////4AAAP//////gAAAP/////8AAAAf/////AAAAA/////4AAAAH/////////w//////////H/////////8//////////z/+H8AAAAAAD8A/wAAAAAAAAD/AAAAAAAAAP8AAAAAAAAA/wAAAAAAAAD+AAAAAAAAAP4AAAAAAAAB/gAAAAAAAAH+AAAAAAAAAfwAAAAAAAAB/AAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP4AAAAAAAAB/gAAAAAAAAH+AAAAAAAAAf8AAAAAAAAD/4AAAAAAAAP/wAAAAAAAB//gAAAAAAAP//AAAAAAAB//+AAAAAAAH8f4AAAAAAA/w/wAAAAAAH+B/gAAAAAA/wD/AAAAAAD+AH+AAAAAAf4AP4AAAAAD/AA/gAAAAAP8AD+AAAAAA/gAP4AAAAAH+AA/gAAAAAf4AD+AAAAAB/AAP4AAAAAH8AA/gAAAAAfwAD+AAAAAD/AAP4AAAAAP4AA/gAAAAA/gAD+AAAAAAAAAAAAAAAA=");

// 64x64
const stick_kick_1 = atob("QEABAAB/+AAAAAAAD///wAAAAAB////4AAAAAf////4AAAAH/////4AAAA//////wAAAH//////gAAA///////AAAH//////+AAAf//////4AAB///////gAAH//////+AAAf///////4AB////////wAD///////+AAH///////4AAP///////AAAf/////v4AAAf////5/gAAAf////P8AAAAP/////wAAAAf////+AAAAH//D//wAAAB//8AH8AAAAf///wAAAAAH////gAAAAA////+AAAAAB///+AAAAAAH//+AAAAAAAAAfwAAAAAAAAB/AAAAAAAAAH8AAAAAAAAAfwAAAAAAAAD/AAAAAAAAAP8AAAAAAAAA/gAfAAAAAAD////AAAAAAP///+AAAAAA////4AAAAAD////gAAAAAP8AH+AAAAAA/gAfwAAAAAD/AB/AAAAAAH8AH8AAAAAAfwA/wAAAAAB/gD/AAAAAAH+AP4AAAAAAP4B/gAAAAAA/wH+AAAAAAD/AHwAAAAAAP8AAAAAAAAB/wAAAAAAAAH+AAAAAAAAA/wAAAAAAAAD+AAAAAAAAAf4AAAAAAAAD/AAAAAAAAAP8AAAAAAAAB/gAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD+AAAAAAAAAAQAAAAAAAAAAAAAAAAAA=");

// 64x64
const stick_kick_2 = atob("QEABAAD/+AAAAAAAP///wAAAAAD////4AAAAA/////4AAAAH/////wAAAB//////wAAAP//////gAAA//////+AAAH//////8AAA///////wAAD///////gAAP//////+AAA///////wAAB///////AAAD//////4AAAP//////gAAAf//////gAAAf//////wAAA//////+AAAAf///8/wAAAAP//+H+AAAAA///A/wAAAAf//+H+AAAAH///+/wAAAB/////+AAAAf/////wAAAA///wf+AAAAB/x/AfwAAAAAAH8AAAAAAAAAfwAAAAAAAAB/gAAAAAAAAH+AAAAAAAAAP4AAAAAAAAA/gAAAADAAAD+AAAAf+AAAP4AAD//8AAA/gAH///wAAD+B////gAAAP////8AAAAA////4AAAAAD//+AAAAAAAP/4AAAAAAAB/wAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAf4AAAAAAAAB/gAAAAAAAAH8AAAAAAAAAfwAAAAAAAAD+AAAAAAAAAP4AAAAAAAAB/gAAAAAAAAH+AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAP4AAAAAAAAB/gAAAAAAAAH8AAAAAAAAA/wAAAAAAAAD/AAAAAAAAAf4AAAAAAAAA/gAAAAAAAAAAAAAAAAAA=");

let stick_index = 0;
const stick_mov =
[
    stick_base,
    stick_jab_l_1,
    stick_jab_l_2,
    stick_jab_l_1,
    stick_base,
    stick_jab_r_1,
    stick_jab_r_2,
    stick_jab_r_1,
    stick_base,
    stick_kick_1,
    stick_kick_2,
    stick_kick_1,
];

I2C1.setup(); // I2C1.setup({bitrate: 100000}); "OVERCLOCK NA COMUNICACAO"
let oled = require("SSD1306").connect(I2C1);

setInterval(function()
{
    oled.clear();
    oled.drawImage(stick_mov[stick_index], 32, 0);
    oled.flip();

    stick_index = (stick_index + 1)%stick_mov.length;
}, 1); // AQUI SETA A VALOCIDADE E REPETIÇÃO, PORM EPODE HAVER UM GARGALO TANTO NA COMUNICAÇÃO I2C1, OU 
// LIMETE DE CLEAR, DRAWIMAGE, FLIP 